name: Docker Image Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  QA-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - name: Deploy
      run: echo "QA Deploy Image"
  Prod-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - name: Deploy
      run: echo "Prod Deploy Image"
