name: Docker Image Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  QA-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: QA Deploy
      run: echo "QA Deploy Image"
    - name: Using Test Secret
      run: |
        echo "${{ secrets.MY_TEST_SECRET }}" >> $GITHUB_ENV
    - name: Print Test Secret
      run: echo $MY_TEST_SECRET

  Prod-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Prod Deploy
      run: echo "Prod Deploy Image"
    - name: Using Prod Secret
      run: |
        echo "${{ secrets.MY_PROD_SECRET }}" >> $GITHUB_ENV
    - name: Print Prod Secret
      run: echo $MY_PROD_SECRET
