name: CI/CD Pipeline
on:
 workflow_dispatch:
   inputs:
     environment:
       description: 'Target environments'     
       required: true

jobs:
 deploy:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       environment: ['dev', 'int', 'stg', 'prod']
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
     - name: Deploy to Environment
       run: echo "Deploying to ${{ matrix.environment }}"
       if: github.event.inputs.environment == matrix.environment
