name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'QA'

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }} Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Environment
        run: |
          case ${{ github.event.inputs.environment }} in
            dev|QA|prod)
              echo "Deploying to ${{ github.event.inputs.environment }} environment"
              # Add deployment steps common for all environments
              ;;
            *)
              echo "Invalid environment specified"
              exit 1
              ;;
          esac
