name: Deploy
on:
  push:
    branches:
      - master
      - Feature/*
jobs:
  deploy:
    name: Deploy to ${{ matrix.environment }} Environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, stage, prod]  # Define all possible environments
    steps:
      - uses: actions/checkout@v3

      - name: Determine Environment based on Branch
        run: |
          if [[ "${{ github.ref }}" == refs/heads/main ]]; then
            environment="[prod,stage]"
          elif [[ "${{ github.ref }}" == refs/heads/Feature/* || "${{ github.ref }}" == refs/heads/develop]]; then
            environment="dev"
            exit 1
          fi
          echo "Deploying to $environment environment"
        shell: bash

      - name: Deploy to Environment
        run: |
          # Access the environment name from the matrix or determined step
          case "$environment" in
            dev)
              echo "Deploying to Dev environment"
              # Add deployment steps specific to dev
              ;;
            stage)
              echo "Deploying to Stage environment"
              # Add deployment steps specific to stage
              ;;
            prod)
              echo "Deploying to Prod environment (**WARNING: Production deployment!**)"
              # Add deployment steps specific to prod (with appropriate safety measures)
              ;;
          esac
